---
- hosts: all
  vars:
    users:
      alice:
        name: Casey M
        telephone: 123-456-7890
      bob:
        name: Bob Banana
        telephone: 987-654-3210
  tasks:
    - name: Print phone records
      debug:
        msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
      loop: "{{ lookup('dict', users) }}"
